package flagx

type SegmentFormatOptions = Flag

const (
	SegmentFormatOptions_cache SegmentFormatOptions = "cache"
	// Allow caching (only affects M3U8 list files).
	SegmentFormatOptions_live SegmentFormatOptions = "live"
	//Allow live-friendly file generation.
)

type SegmentListType = Flag

const (
	SegmentListType_flat SegmentListType = "flat"

	//Generate a flat list for the created segments, one segment per line.

	SegmentListType_ext SegmentListType = "ext"
	SegmentListType_csv SegmentListType = "csv"
	//Generate a list for the created segments, one segment per line, each line matching the format (comma-separated values):
	//segment_filename,segment_start_time,segment_end_time
	//segment_filename is the name of the output file generated by the muxer according to the provided pattern. CSV escaping (according to RFC4180) is applied if required.
	//segment_start_time and segment_end_time specify the segment start and end time expressed in seconds.
	//A list file with the suffix ".csv" or ".ext" will auto-select this format.
	//‘ext’ is deprecated in favor or ‘csv’.

	SegmentListType_ffconcat SegmentListType = "ffconcat"
	//Generate an ffconcat file for the created segments. The resulting file can be read using the FFmpeg concat demuxer.
	//A list file with the suffix ".ffcat" or ".ffconcat" will auto-select this format.

	SegmentListType_m3u8 SegmentListType = "m3u8"
	//Generate an extended M3U8 file, version 3, compliant with http://tools.ietf.org/id/draft-pantos-http-live-streaming.
	//A list file with the suffix ".m3u8" will auto-select this format.
)
